spring.application.name=ucomap-backend

spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://admin:eWxxjXuVWRRNRCqS@ucomap.02mi34n.mongodb.net/ucoCampusMap?appName=UcoMap}

server.port=8080

app.data.init-on-startup=true

app.cors.allowed-origins=*

app.jwt.secret=1SsyHO3koQR14gUS96g7fxs6eafNVH8xmLpGEBRKFrbtFJYpPR
app.jwt.expiration-ms=86400000

app.rate-limit.max-requests=30
app.rate-limit.window-seconds=60
app.rate-limit.trusted-proxies=RATE_LIMIT_TRUSTED_PROXIES

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ucomap.admin@gmail.com
spring.mail.password=udmuvhpsqpjsznga
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.password-reset.token-expiry-minutes=60
app.password-reset.frontend-url=https://uco-map.netlify.app/
app.password-reset.reset-path=/reset-password
app.password-reset.cooldown-minutes=1
app.password-reset.email-subject=Restablecer credenciales — UCO Map

logging.level.co.edu.uco.ucomap=WARN
logging.level.org.springframework.data.mongodb=WARN